// Action naming convention: <NOUN>_<VERB>
export const WORKPLACE_ADD = 'WORKPLACE_ADD';
export const WORKPLACE_UPDATE = 'WORKPLACE_UPDATE';
export const WORKPLACE_REMOVE = 'WORKPLACE_REMOVE';
export const WORKPLACE_SELECT = 'WORKPLACE_SELECT';
export const WORKPLACE_FETCH = 'WORKPLACE_FETCH';
export const WORKPLACE_FETCH_SUCCESS = 'WORKPLACE_FETCH_SUCCESS';
export const WORKPLACE_FETCH_FAILURE = 'WORKPLACE_FETCH_FAILURE';

export const TOOLS_MEASURE_TOGGLE = 'TOOLS_MEASURE_TOGGLE';
export const PRODUCTION_HALL_UPDATE = 'PRODUCTION_HALL_UPDATE';
export const PRODUCTION_HALL_LAYOUT_CLEAR = 'PRODUCTION_HALL_LAYOUT_CLEAR';

export const PRODUCTION_HALL_WITH_WORKPLACES_FETCH = 'PRODUCTION_HALL_WITH_WORKPLACES_FETCH';
export const PRODUCTION_HALL_WITH_WORKPLACES_SEND = 'PRODUCTION_HALL_WITH_WORKPLACES_SEND';
export const PRODUCTION_HALL_WITH_WORKPLACES_SEND_SUCCESS = 'PRODUCTION_HALL_WITH_WORKPLACES_SEND_SUCCESS';
export const PRODUCTION_HALL_WITH_WORKPLACES_SEND_FAILURE = 'PRODUCTION_HALL_WITH_WORKPLACES_SEND_FAILURE';

export const PROCESS_ADD = 'PROCESS_ADD';
export const PROCESS_SELECT = 'PROCESS_SELECT';

export const OPERATIONS_FETCH = 'OPERATIONS_FETCH';
export const OPERATIONS_FETCH_SUCCESS = 'OPERATIONS_FETCH_SUCCESS';
export const OPERATIONS_FETCH_FAILURE = 'OPERATIONS_FETCH_FAILURE';
export const OPERATION_ADD = 'OPERATION_ADD';
export const OPERATION_REMOVE = 'OPERATION_REMOVE';
export const OPERATION_REMOVE_ALL = 'OPERATION_REMOVE_ALL';

export const SVG_WORKPLACE_PICTURE_VISIBILITY_CHANGE = 'SVG_WORKPLACE_PICTURE_VISIBILITY_CHANGE';

export const UI_SELECTED_ITEMS_ACTIVE_TAB_CHANGE = 'UI_SELECTED_ITEMS_ACTIVE_TAB_CHANGE';